name: snow
description: A coding contests reminder app. Supports 10+ widely used platforms.

publish_to: "none"

version: 1.1.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  # NOTE: Keep bloc packages 7.x.x, because hydrated bloc crashing on 8.x.x

  equatable: ^2.0.0
  dynamic_color: ^1.4.0
  cupertino_icons: ^1.0.2
  flutter_bloc: ^7.1.1
  url_launcher: ^6.1.5
  date_format: ^2.0.7
  duration: ^3.0.12
  share_plus: ^5.0.0
  hydrated_bloc: ^7.1.0
  path_provider: ^2.0.11
  json_annotation: ^4.7.0
  optimize_battery: ^0.0.4
  awesome_notifications: ^0.7.2
  flutter_launcher_icons: ^0.10.0
  flutter_material_color_picker: ^1.1.0+2
  material_design_icons_flutter: ^5.0.6996

  contests_repository:
    path: packages/contests_repository

  duration_picker_dialog_box:
    path: packages/duration_picker_dialog_box

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.0.0
  json_serializable: ^6.0.0

flutter:
  uses-material-design: true
