name: contests_repository
description: Repository for providing contests.

publish_to: none

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  uuid: ^3.0.6
  http: ^0.13.5
  equatable: ^2.0.0
  shared_preferences: ^2.0.15
  